### ISSUE TITLE
Supporto formato EPUB

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread#4]

**Comment by pbroglio** [comment]
[EPUBLIB - gestione di file .epub](http://www.siegmann.nl/epublib/android)

**Comment by czanacch** [comment]
Ricordiamo che la classe sarà EPubDocument, sottotipo di Document, come avevamo da sempre specificato in fase ST.

**Comment by czanacch** [comment]
Sono riuscito in locale a estrapolare il testo in chiaro di un qualsiasi file .epub (ovvero la sua parte html escludendo tutti i tag) con l'aiuto di questa libreria: [https://github.com/mertakdut/EpubParser]
Con la libreria suggerita da Paolo purtroppo non sono riuscito.
Dobbiamo ora decidere se lasciare così le cose per quanto riguarda il formato ePub (e magari arricchire l'applicazione con altri formati) oppure scendere nel dettaglio e cercare di creare la lista per i capitoli ecc...
